Buzzer implementation
melkati/CO2-Gadget pull request #153
Opened 2024-02-01 02:42 UTC by Coscolin

Added buzzer alarm and configuration in menu.

Alarm: ON / OFF
Repeat: ONCE / EVERY
Each: 5s / 10s / 15s / 30s / 1m / 2m / 5m
Tone: HIGH / MED. / LOW
Span: SHORT / MED / LONG

Inside menu buzzer is silenced.

Tested and work correctly.

TODO: save changes in memory

2024-02-01 09:38 UTC, Coscolin commented
@melkati , the file [WiFiMenu.h] it's not necesary to commit.

It's for another implementation and is still in develpment.

Don't import it to master.

I'm sorry, I'm still learning GitHub metodology.

2024-02-01 10:44 UTC, melkati commented
> Alarm: ON / OFF
> Repeat: ONCE / EVERY
> Each: 5s / 10s / 15s / 30s / 1m / 2m / 5m
> Tone: HIGH / MED. / LOW
> Span: SHORT / MED / LONG

What's Repeat, Each, Span, intended for?

I will leave some comments in the PR as I review it.

I see this PR implements buffer control ("hardware" control) and also menu modification. Please separate both in two PR for enhanced manageability.

Thank you! 😀

2024-02-01 10:46 UTC, melkati commented
As including this feature is not easy and touches many things in CO2 Gadget, I created a new branch (feature-buzzer) for it, so we can merge it once everything is complete.

2024-02-01 12:53 UTC, melkati requested changes

2024-02-01 23:34 UTC, Coscolin commented on CO2_Gadget_Buzzer.h
> +int lowestco2=10000;
Not necessary. It was a failed previous way to implement repeat buzzer only once.

2024-02-02 00:10 UTC, Coscolin commented on CO2_Gadget_Buzzer.h
> +void buzzerLoop(){
Only block during sound, about 0.3sec to 1sec.
To non blocking strategy we can use ticker library:
https://techtutorialsx.com/2021/08/07/esp32-ticker-library/

2024-02-02 00:25 UTC, Coscolin commented on CO2_Gadget_Buzzer.h
> +    if ((millis() - lastTimeAlarmBeep >= timeBetweenAlarmBeep * 1000) || (lastTimeAlarmBeep == 0)) {
It's a good idea. Done.

2024-02-02 06:38 UTC, Coscolin commented on CO2_Gadget_Menu.h
> +TOGGLE(activeAlarm, activeAlarmOffMenu, "Alarm: ", doNothing, noEvent, wrapStyle
I have changed Alarm to Buzzer but I don't knowc how to divide PR.

2024-02-02 09:33 UTC, Coscolin commented
> > Alarm: ON / OFF
> > Repeat: ONCE / EVERY
> > Each: 5s / 10s / 15s / 30s / 1m / 2m / 5m
> > Tone: HIGH / MED. / LOW
> > Span: SHORT / MED / LONG
> 
> What's Repeat, Each, Span, intended for?
> 
> I will leave some comments in the PR as I review it.
> 
> I see this PR implements buffer control ("hardware" control) and also menu modification. Please separate both in two PR for enhanced manageability.
> 
> Thank you! 😀

- REPEAT ONCE: Only buzzer one time orange or red CO2 range is raised. Don't buzzer again until CO2 values downs "HYSTERIC" value down orange/red range and raise again.
- REPEAT EVERY: Buzzer all time while CO2 values are upper orange or red range.
- EACH: time between buzzers if repeat is "EVERY"
- TONE: Frecuency of buzzer tone. 
- SPAN: Duration of buzzer tones.

2024-02-02 11:03 UTC, melkati commented
Continues in #157 and #153

2024-02-02 11:03 UTC, closed without merging